export default interface Aggregates {
    numberOfDoctors: number,
    numberOfPharmacists: number,
    numberOfPharmacyTechnicians: number,
    numberOfDentists: number,
    numberOfDentalTechnicians: number,
    numberOfNurses: number,
    numberOfMidwifes: number,
    numberofLabTechnicians: number,
    numberOfLabScientists: number,
    healthRecordAndHIMOfficers: number,
    numberOfCommunityHealthWorkers: number,
    numberOfCommunityHealthExtensionWorker: number,
    numberOfJuniorComHealthExtensionWorker: number,
    numberOfEnvironmentalHealthOfficers: number,
    numberOfHealthAttendantOrAssistant: number,
    status: boolean,
    lastSynced: Date,
}
